apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-app
  namespace: production
  labels:
    app: utility-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: utility-app
  template:
    metadata:
      labels:
        app: utility-app
        environment: production
    spec:
      containers:
      - name: utility-container
        image: noelav07/utility:2.0  #production image
        ports:
        - containerPort: 8090
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
