apiVersion: v1
kind: Service
metadata:
  name: ailon-service
  namespace: staging
  labels:
    app: ailon-app
    environment: staging
spec:
  selector:
    app: ailon-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: ClusterIP
