apiVersion: v1
kind: Service
metadata:
  name: staging-utility
  namespace: staging
  labels:
    app: utility-app
    environment: staging
spec:
  selector:
    app: utility-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: LoadBalancer
