apiVersion: v1
kind: Service
metadata:
  name: utility-service
  namespace: production
  labels:
    app: utility-app
    environment: production
spec:
  selector:
    app: utility-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: ClusterIP

